people:
  Felix: <replace-from-yaml>
  John: <replace-from-yaml>

realised:
  5:
    - Carbon capture
    - First man turns 150
    - Fusion

weights:
  timestamps: 10
  order: 1
# Remark: Currently the timestamps are not included in the evaluation.

out_path: data/08_reporting/results_<person_key>/<event>.csv
